#!/bin/bash
time=$(date +%H:%M)
uptime=$(w | grep console | awk '{print $5}')
uname=$(uname -n | rev | cut -c 8- | rev)
c0="$(tput setaf 2)"
nc="$(tput sgr0)"

cat <<EOF
${c0}                 
${c0}       .::    .::.            user   : ${nc}${USER}
${c0}    +:+:+   +:    +:          post   : ${nc}${uname}
${c0}     +:+   +:    +:           time   : ${nc}${time}
${c0}    #+#     #+#+#+            uptime : ${nc}${uptime}
${c0}   #+#         ##
${c0}  ###    #+.  #+
${c0}            
EOF
